# Tensorflow Basics

In [1]:
import tensorflow as tf
print ('tf version:', tf.__version__)

tf version: 1.13.1


## Tensors

In [2]:
girl_friend = tf.constant('Shaoyun Dong')

In [3]:
type(girl_friend)

tensorflow.python.framework.ops.Tensor

In [4]:
city = tf.constant('Beijing')

In [8]:
print (city.dtype, '\n', type(city))

<dtype: 'string'> 
 <class 'tensorflow.python.framework.ops.Tensor'>


In [9]:
sentence = girl_friend + city

In [11]:
sentence, type(sentence)

(<tf.Tensor 'add:0' shape=() dtype=string>,
 tensorflow.python.framework.ops.Tensor)

In [12]:
with tf.Session() as sess: #the session is automatically closed when finished
    sentence = sess.run(sentence)

In [22]:
sentence

b'Shaoyun DongBeijing'

In [23]:
sentence_2 = girl_friend + city

In [24]:
sentence_2

<tf.Tensor 'add_1:0' shape=() dtype=string>

In [25]:
sentence_3 = girl_friend + city

In [26]:
sentence_3

<tf.Tensor 'add_2:0' shape=() dtype=string>

In [27]:
result = tf.constant(2) + tf.constant(3)

In [28]:
result

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [29]:
sess

In [30]:
#the following close() statement is equivalent to the with statement above.
sess.close()

In [31]:
sess

## Operations

In [38]:
const = tf.constant(10)
with tf.Session() as sess: #in order to find out what the value contained in this variable, we must run a session to find out.
    result = sess.run(const)
result

10

In [39]:
fill_mat = tf.fill((4, 3), 2)
with tf.Session() as sess:
    result = sess.run(fill_mat)
result

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [43]:
zeros = tf.zeros((2, 3))
ones = tf.ones((2, 4))
with tf.Session() as sess:
    my_zeros = sess.run(zeros)
    my_ones = sess.run(ones)
print (my_zeros, '\n\n', my_ones)

[[0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [84]:
#set the random seed to always get the same random numbers
rand_normal = tf.random_normal((3, 4), mean=0, stddev=0.5, seed=2)
rand_uniform = tf.random_uniform((2, 3), minval=0, maxval=1, seed=2)
with tf.Session() as sess:
    my_rand_normal = sess.run(rand_normal)
    my_rand_uniform = sess.run(rand_uniform)
    
    print (my_rand_normal, '\n\n', my_rand_uniform)

[[-0.42905542 -0.09831149  0.06947523 -0.6106384 ]
 [-0.20170642 -0.57270205  0.31991202 -0.78830594]
 [-0.5130053   0.31425416 -0.41411188  0.17333858]] 

 [[0.6787466  0.7141509  0.46981692]
 [0.4819697  0.47838175 0.55389535]]


In [69]:
test_sess = tf.InteractiveSession()

#the following command setting random seed is not working well
#so the random seed has to be set in the random function call.
tf.set_random_seed(2) #!!!!

rand_test = tf.random_normal((2,3), mean= 0, stddev = 0.2)
print (rand_test.eval())
test_sess.close()

[[-0.13607174  0.00201129 -0.24960096]
 [ 0.28463793  0.0857311   0.02762316]]


In [90]:
with tf.Session() as sess:
    print (sess.run(tf.constant(2)))

2


## Interactive Session

Useful for notebook sessions

In [106]:
sess = tf.InteractiveSession()#now we are in an active session

In [107]:
ones.eval()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [108]:
for operation in [const, fill_mat, zeros, ones, rand_normal, rand_uniform]:
    print (operation.eval(), '\n\n')

10 


[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]] 


[[0. 0. 0.]
 [0. 0. 0.]] 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


[[-0.42905542 -0.09831149  0.06947523 -0.6106384 ]
 [-0.20170642 -0.57270205  0.31991202 -0.78830594]
 [-0.5130053   0.31425416 -0.41411188  0.17333858]] 


[[0.6787466  0.7141509  0.46981692]
 [0.4819697  0.47838175 0.55389535]] 




In [109]:
ones.eval()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [110]:
sess.close() #session is closed

ones.eval() #ERROR!!! no active session is available, so can not run operations.

## Matrix Multiplication

In [112]:
a = tf.constant([[2, 3], [4, 5]])

In [114]:
a_shape = a.get_shape()

In [120]:
type(a_shape[0])

tensorflow.python.framework.tensor_shape.Dimension

In [118]:
t = int(a_shape[0])

In [119]:
t+2

4

In [122]:
b = tf.constant([[4], [7]])

In [123]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [126]:
result = tf.matmul(a, b)
#start a new interactive session
sess = tf.InteractiveSession()
result.eval()

array([[29],
       [51]], dtype=int32)

In [127]:
tf.get_default_graph

<function tensorflow.python.framework.ops.get_default_graph()>

In [128]:
tf.get_default_session

<function tensorflow.python.framework.ops.get_default_session()>

In [130]:
sess is tf.get_default_session

False

In [131]:
sess